// React/src/App.tsx
import './App.css';
import 'devextreme/dist/css/dx.fluent.blue.light.css';
import { Button } from 'devextreme-react/button';
import { Tooltip } from 'devextreme-react/tooltip';

function likeRender(): JSX.Element {
  return <div>Like</div>;
}

function trashRender(): JSX.Element {
  return (
    <div className='red-tooltip'>Delete</div>
  );
}

function infoRender(): JSX.Element {
  return (
    <div className='blue-tooltip'>Info</div>
  );
}

function App(): JSX.Element {
  return (
    <div className="dx-viewport">
      <div className="buttons">
        <Button
          id="like"
          icon="like"
        />
        <Button
          id="trash"
          icon="trash"
        />
        <Button
          id="info"
          icon="info"
        />
      </div>
      <div className="tooltips">
        <Tooltip
          target="#like"
          showEvent="mouseenter"
          hideEvent="mouseleave"
          contentRender={likeRender}
        />
        <Tooltip
          target="#trash"
          showEvent="mouseenter"
          hideEvent="mouseleave"
          contentRender={trashRender}
        />
        <Tooltip
          target="#info"
          showEvent="mouseenter"
          hideEvent="mouseleave"
          contentRender={infoRender}
        />
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { DxButtonModule } from 'devextreme-angular/ui/button';

@Component({
    selector: 'app-root',
    imports: [DxButtonModule],
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'Angular';
}

<div class="dx-viewport">
  <div class="buttons">
    <dx-button id="like" icon="like"></dx-button>
    <dx-button id="trash" icon="trash"></dx-button>
    <dx-button id="info" icon="info"></dx-button>
  </div>
  <div class="tooltips">
    <dx-tooltip
      target="#like"
      showEvent="mouseenter"
      hideEvent="mouseleave"
      contentTemplate="Like"
    >
    </dx-tooltip>
    <dx-tooltip
      target="#trash"
      showEvent="mouseenter"
      hideEvent="mouseleave"
      contentTemplate="trashTooltip"
    >
      <div *dxTemplate="let model of 'trashTooltip'">
        <div class="red-tooltip">
          <span class="tooltip-text">Delete</span>
        </div>
      </div>
    </dx-tooltip>
    <dx-tooltip
      target="#info"
      showEvent="mouseenter"
      hideEvent="mouseleave"
      contentTemplate="infoTooltip"
    >
      <div *dxTemplate="let model of 'infoTooltip'">
        <div class="blue-tooltip">
          <span class="tooltip-text">Info</span>
        </div>
      </div>
    </dx-tooltip>
  </div>
</div>
